### ISSUE TITLE
小米手机有更改屏幕分辨率的操作，更换后，手机的物理尺寸就错了

### ISSUE THREAD

**Issue by billsinla** [z244370114/DeviceLibray#1]

**Comment by z244370114** [comment]
你说的这种情况没有遇到过哦！具体可能需要你自行测试！如果你是使用设备唯一ID的话。则不需要担心它更改的操作。

**Comment by billsinla** [comment]
嗯嗯，测试过了，只改变了屏幕像素分辨率，但是xdpi ydpi 没有改变， 所以会导致算出来的物理尺寸偏小

**Comment by z244370114** [comment]
好的！这个库主要的用途是。拿到手机所有的用户信息，方便进行风控。从你所描述，我理解的你只是想拿数据做一些屏幕适配工作。

**Comment by huosange** [comment]
![image](https://user-images.githubusercontent.com/4567729/178867219-0643f4d6-9355-4a87-8c90-937224f1972a.png)，这里是咋解决的

**Comment by z244370114** [comment]
> ![image](https://user-images.githubusercontent.com/4567729/178867219-0643f4d6-9355-4a87-8c90-937224f1972a.png)，这里是咋解决的
看一下是不是，读写权限没有开启！你这个是没有找到此文件呀。
