### ISSUE TITLE
can't find symbol

### ISSUE THREAD

**Issue by yt997** [z244370114/DeviceLibray#10]
home/yt/sources/DeviceLibray/devicelibrary/src/main/java/com/zy/devicelibrary/data/StorageData.java:4: error: cannot find symbol
import com.zy.devicelibrary.utils.StorageClassSizeUtils;
                                 ^
  symbol:   class StorageClassSizeUtils
  location: package com.zy.devicelibrary.utils

**Comment by z244370114** [comment]
已修复
