### ISSUE TITLE
deviceId 会不固定，没有卸载的情况下也会出现改变的情况

### ISSUE THREAD

**Issue by laitte-J** [z244370114/DeviceLibray#6]
![image](https://github.com/z244370114/DeviceLibray/assets/10041112/b53d5e81-4227-4487-8105-5a0ffa45bcba)

**Comment by z244370114** [comment]
没道理呀！手机读写权限是否开启

**Comment by z244370114** [comment]
如果想设备ID唯一，首先要确保手机读写权限已开启！
