### ISSUE TITLE
同型号手机DeviceId一样

### ISSUE THREAD

**Issue by pangli** [z244370114/DeviceLibray#7]

**Comment by z244370114** [comment]
不会的

**Comment by pangli** [comment]
我的两台三星 Galaxy A03 SM-A035F/DS 获取到的值完全一样，都是 0d261b28ebb115612f4b5e73825a99e4

**Comment by z244370114** [comment]
需要先开启读写权限

**Comment by pangli** [comment]
![image](https://github.com/z244370114/DeviceLibray/assets/7498978/16e7f222-981f-4d5a-ba5f-47efd464f9f6)
我直接调用的是这个方法跟读写权限无关，如果读写权限会影响Deviceid的生成结果，那么就不能算作唯一了，因为有读写权限和没读写权限对值是有影响的。

**Comment by z244370114** [comment]
可以先开读写权限 在试一下

**Comment by pangli** [comment]
不止读写权限，我开了很多权限，权限肯定是有的

**Comment by z244370114** [comment]
你手机插卡了吗

**Comment by pangli** [comment]
插了，我认为插不插卡也不能影响最后的值，如果插卡和不插卡值不一样那么就不能叫唯一设备标识了

**Comment by z244370114** [comment]
[https://blog.csdn.net/u013290250/article/details/118580373?spm=1001.2014.3001.5502](url)
可以浏览我之前写的文章，讲的生成ID的业务逻辑。你可以debug研究
